#!/bin/sh

echo '🏗️ Running pre-commit checks...'

# Check and fix Prettier standards
npm run format || (
    echo '🚫 Prettier Check Failed. Please review the changes and try again.';
    exit 1;
)

# Check ESLint Standards
npm run check-lint || (
    echo '🚫 ESLint Check Failed. Please make the required changes, add them, and try again.';
    exit 1;
)

# Check TypeScript standards
npm run check-types || (
    echo '🚫 TypeScript Check Failed. Please address the issues, add the changes, and try again.';
    exit 1;
)

# If everything passes... Now we can build
echo '🔍 All checks passed. Building the project...'

npm run build || (
    echo '🚫 Build Failed. Please review the errors above and try again.';
    exit 1;
)

# If everything passes... Now we can commit
echo '✅ All checks and build passed. Proceeding with commit.'
